### ISSUE TITLE
Get listed on the FMI Tools page

### ISSUE THREAD

**Issue by chrbertsch** [Fraunhofer-IIS/fmugym#1]
I would like to encourage you to get your tool fmugym listed on the FMI tools page https://fmi-standard.org/tools/, see https://github.com/modelica/fmi-standard.org/blob/master/CONTRIBUTING.md#updating-the-tools-list for instructions.

**Comment by wredsen** [comment]
Thank you for making me aware of this opportunity, I just created a [PR](https://github.com/modelica/fmi-standard.org/pull/645) :)
